### ISSUE TITLE
raise exception_class(message, screen, stacktrace)

### ISSUE THREAD

**Issue by datomnurdin** [lalongooo/selenium-fb-group-poster#4]
I got this error message when trying posting.

```
Traceback (most recent call last):
  File "fbposter.py", line 87, in <module>
    main()
  File "fbposter.py", line 61, in main
    addMediaButton.click()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <span class="_5qtp">...</span> is not clickable at point (473, 458). Other element would receive the click: <div class="_3ixn"></div>
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.13.6 x86_64)
```

Please advice. Thank you.

**Comment by iharshit009** [comment]
actually i face the same error when posting the description through selenium but then I made changes to xpath and then the code ran...

this error basically means that selenium cannot find the xpath which you have described..
